### ISSUE TITLE
compositeOnly does not respect ignoreTransparency

### ISSUE THREAD

**Issue by 719media** [justintaddei/v-shared-element#14] opened 2020-06-11 20:17 UTC
When setting option compositeOnly: true on a div containing an image, the div unexpectedly does a fade out. I understood this setting to only have an effect on performance, and removing border-radius transitions. I'll try to come up with a reproduction.

**Comment by 719media** [comment] 2020-06-11 20:23
See
https://codesandbox.io/s/v-shared-element-compositeonly-ux69q

If you remove compositeOnly setting, then fade will no longer happen, as desired.

**Comment by justintaddei** [comment] 2020-06-11 20:32
The fade is something that I expect to happen. What I wasn't expecting is that it "pops" to the new shape.

Is should look like the gif in the docs:

![](https://raw.githubusercontent.com/justintaddei/v-shared-element/assets/compositeOnly.gif)

The reason for the fade was to "blend" them better during the transition (basically just a cross fade). If there's a behavior  you think would be better, I'm open to changing it.



I'm currently out of town and away from my computer so I can't experiment for a day or two

**Comment by 719media** [comment] 2020-06-12 02:50
I was under the impression that using `ignoreTransparency: true` would make the transparency fade not happen.

**Comment by justintaddei** [comment] 2020-06-12 02:57
Ah yes. I see your point. `ignoreTransparency` should definitely override the fade introduced by `compositeOnly`. That comes from illusory so have I'll change the behavior there first.

I should be back in town by June 13th (provided everything goes already on the road) so I'll push an update then and report back.

**Comment by justintaddei** [comment] 2020-06-13 21:46
This is now fixed in illusory and will propagate here after the release of illusory@1.5.0

Regarding the "pop"
> The fade is something that I expect to happen. What I wasn't expecting is that it "pops" to the new shape.

I've identified the cause so it will be fixed in v1.5.0 as well.

**Closed** 2020-10-27 02:30 UTC
Labels: bug
