### ISSUE TITLE
Vue3??

### ISSUE THREAD

**Issue by nicolidin** [justintaddei/v-shared-element#25] opened 2021-06-10 10:35 UTC
Does it works with vue3 ? 
I have an error that seems to be related with Vue3!

**Comment by justintaddei** [comment] 2021-06-10 15:28
Not yet, unfortunately. This project is absolutely still maintained and I have plans for vue3 support. I've been dealing with a bunch of stuff (new job, broken down car, etc.) lately so it's taking longer than I would like. I'll hopefully have time to work on it within a couple of weeks.

PRs are welcome 😁

**Comment by justintaddei** [comment] 2021-07-01 04:23
Closing because this is a duplicate of #24 

Vue3 support is now under active development.

**Closed by justintaddei** 2021-07-01 04:23 UTC
Labels: duplicate
